### ISSUE TITLE
Documentation compatible with pypi

### ISSUE THREAD

**Issue by mn5hk** [mn5hk/pyshbundle#31]

**Comment by abhimhamane** [comment]
Sorry to bother you again, but I found some functions with missing documentation. There are no doc strings for functions like `clm2cs`, `clm2sc`, `eigengrav`, `klm2sc`,  many more they only have script docstrings and acknowledgements.



![Screenshot from 2023-04-07 20-11-40](https://user-images.githubusercontent.com/97011961/230632632-35942a99-1c68-4cba-9f4b-63d48e824d4c.png)

**Comment by mn5hk** [comment]
Hi @abhimhamane ,

Thanks for pointing this out. I will follow up in a few days.

Best,
AS
c.c. @lsmvivek

**Comment by abhimhamane** [comment]
Hi @mn5hk @lsmvivek ,

This is related to the presentation and styling of the code. It is generally a best practice to make the code compliant with the PEP8 Python style guide. It will make the codebase more consistent and accessible. I saw some minor inconsistencies in the spacing and commenting.

Some examples:
1. Line no: 51, 59, 64 could have used `#` instead to `''' ... '''` for single line comments
2. In order to make code more readable we could use consistent spacing like in line no 58 
3. For showing operator precedence we could use spacing properly.
4. `degree_order=int((Lmax+1)*(Lmax+2)/2)` reads better if it were `degree_order = int((Lmax+1) * (Lmax+2)/2)`

I'm not sure about this one, but what is the difference between importing a module within and outside the function? I have rarely seen modules being imported within a function.

I would like to know your thoughts on this. It would be a straightforward task for me to fix as a newbie.

Best,
Abhishek

![Screenshot from 2023-04-07 23-54-54](https://user-images.githubusercontent.com/97011961/230658883-1706eaf2-45cc-47d7-ac99-876fb3a2cc7a.png)

**Comment by mn5hk** [comment]
Hi @abhimhamane,

Right now, our next task would be to build a quality documentation. Substantial work has taken place in the direction already, but it still needs further inputs to be finalized.

Before we further proceed, two different approaches to documentation can be done: my preference would be to get both of them done (although one could also be enough). These are:
- A github wiki page https://github.com/mn5hk/pyshbundle/wiki
- A github pages document https://mn5hk.github.io/pyshbundle/

In the github wiki page, we have provided documentation for most of the codes already. As you have rightly pointed out earlier in the thread, some of the codes are still missing some documentation (https://github.com/mn5hk/pyshbundle/issues/31#issuecomment-1500379188). For the codes missing documentation, I will need to support you closely. I will try to do it, rather slowly, over few weekends.

For the codes for which documentation already exists, these were first written (before ensuring pip compatibility) as independent program documentation. Could you edit it in a way to make it in sync with the new changes and pypi compatibility? Additionally, the formatting is rather rough on the document. Feel free to work around and make it look better.

I would recommend you to create a new github wiki page (https://github.com/mn5hk/pyshbundle/wiki), and start merging all the other wiki page information there. You can start editing the documentation for pypi compatibility as well as better formatting. Once this is ready, we will add the same content to the github pages document as well.

Once this step is completed, I expect the package to be near completion for the first draft release. After this, we can maybe discuss how to take the project even further at some point.

Thanks a lot for your contributions,
AS

**Comment by abhimhamane** [comment]
Hello @mn5hk ,

Apologies for the delayed response. It's actually the last week of this semester, so a bit busy with assignments, projects and other deadlines before the end-sem exam. 

It's a good idea to develop both the GitHub Wiki and Documentation webpage using GitHub Pages. Sure, I'll first complete the documentation of functions with doc strings. I can work with you later, whenever you're free, for those function which do not have doc strings.

I'll review the PyPi Documentation guidelines and report with the major styling and formatting recommendations. After which, I can format the codebase to ensure compatibility.

P.S. Can you update the `paper_abhimhamane.pdf` with the latest one, I think the latest one should not have any formatting or affiliation related errors. Latest one after the build - [paper_joss_latest.pdf](https://github.com/mn5hk/pyshbundle/files/11247564/paper_joss_latest.pdf)

Regards,
Abhishek

**Comment by mn5hk** [comment]
Sounds great

**Comment by abhimhamane** [comment]
Hi @mn5hk ,

I was thinking that do we need the license, acknowledgement and referred papers to be included in each of the file. I was thinking we can remove it and have this info in the README alone.

![Screenshot from 2023-04-20 00-32-19](https://user-images.githubusercontent.com/97011961/233175185-f9fa18fc-d524-4c5d-9746-3b3553db159c.png)

As I mentioned earlier, the convention in Python is to use `snake_case` for variable and function naming, I found that some sections have `camelCase` or `PascalCase`. Should we change it or let it be for the time being?

![Screenshot from 2023-04-20 00-40-28](https://user-images.githubusercontent.com/97011961/233177478-a8f603a5-cd1e-4cf0-8554-62fe98a759e4.png)

Let me know what do you think.

Regards,
Abhishek

**Comment by mn5hk** [comment]
Hi @abhimhamane ,

Thanks for pointing out the issues. Let them both be as it is for now..

Best,
AS

**Comment by abhimhamane** [comment]
Hi @mn5hk ,

I have solved the math-markdown error in the `docs/index.md`. I guess you had setup `MkDocs` to build the docs. In order to interpret the LaTeX code, `mkdocs.yml` needed a `MathJx`extension. I have added that and I build it on my local machine and its working.
![Screenshot from 2023-04-20 15-31-07](https://user-images.githubusercontent.com/97011961/233334075-231b4011-7dea-41a3-b5ad-eda8a27b730c.png)

I tried changing the theme to the popular `Read-the-Docs`. If its not useful I can revert back to the original `material` theme.

Regards,
Abhishek

**Comment by abhimhamane** [comment]
Thanks @mn5hk , I merged the changes but its not getting reflected in the github pages site. Can you tell me how did you setup the github actions for automated deployment. I do not find any `.github/workflow` file for the site deployment.

**Comment by mn5hk** [comment]
@abhimhamane I believe the doc file is made; when I implemented the following tutorials for publishing Python package with pypi:
- https://www.youtube.com/watch?v=DAPAv9KbYZ0&list=PLAxJ4-o7ZoPeUqGpMhvJoVk5G-TrvMAd-&index=12
- https://www.youtube.com/watch?v=7FcX9uWDuIQ&list=PLAxJ4-o7ZoPeUqGpMhvJoVk5G-TrvMAd-&index=12

Feel free to go through them in your free time.

Also, can you share the updated draft paper with me? I will share it with the team for review.

Best,
AS

**Comment by abhimhamane** [comment]
Hi @mn5hk , There is some issue with the `mkdocs.yml` and `ci-docs-gh-pages.yml` I edited those to test out the static docs website on my forked repo. But I guess I was not cautious enough while creating a pull request. I'll make the necessary changes and make sure this does not happen again. Like I said yesterday, I cannot figure out why the docs does not seem to work, it worked fine when I served it on my `locahost:8000`.

Regards,
Abhishek

**Comment by mn5hk** [comment]
@abhimhamane I have my suspisions that running the setup.py file should make it work; I will check it over some weekend.

Thanks,
AS

**Comment by abhimhamane** [comment]
Hi @mn5hk , I guess I found the issue. I hosted the docs on my gh-page (https://abhimhamane.github.io/pyshbundle/). Due to my previous commit there is a new branch `gh-pages` in the repo. Can you try changing the pages setting for this repo from `main` branch to `gh-pages` branch.

![Screenshot from 2023-04-22 02-15-01](https://user-images.githubusercontent.com/97011961/233731691-5d3bde8a-80e8-46a8-b2f6-80efddff961b.png)

**Comment by mn5hk** [comment]
Hi @abhimhamane, thanks for the update. I just changed the branch to `gh-pages` as you have requested. However, it does not appear to affect the page. I will let it be for some time, just in case it takes time to refresh (highly unlikely imo).

<img width="559" alt="image" src="https://user-images.githubusercontent.com/65601810/233832553-11d0c3a8-5343-494b-ad55-7731d7791bc2.png">

**Comment by abhimhamane** [comment]
Hi @mn5hk , you have selected the `/docs`. I think it should be `/root` instead, cause the `index.html` is in the root folder of `gh-pages`.

**Comment by mn5hk** [comment]
Hi @abhimhamane thanks. The update has been made and is successful.
<img width="827" alt="image" src="https://user-images.githubusercontent.com/65601810/233836040-b000aa7f-d9ed-4f94-aeb8-a81f1f41a100.png">
